name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - '**'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Pass
        run: /bin/true
